services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    restart: unless-stopped
    environment:
      TZ: America/Vancouver
      CRON: "*/15 * * * *"
      PRIMARY: https://${primary}|${password}
      REPLICAS: https://pihole|${password}
      SYNC_CONFIG_DNS: true
      SYNC_GRAVITY_AD_LIST: true
      SYNC_GRAVITY_AD_LIST_BY_GROUP: true
      SYNC_GRAVITY_DOMAIN_LIST: true
      SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP: true
      CLIENT_SKIP_TLS_VERIFICATION: true
      SYNC_GRAVITY_GROUP: true
      SYNC_GRAVITY_CLIENT: true
      SYNC_GRAVITY_CLIENT_BY_GROUP: true
      FULL_SYNC: false
      RUN_GRAVITY: false
      SYNC_CONFIG_DHCP: false
      SYNC_CONFIG_NTP: false
      SYNC_CONFIG_RESOLVER: false
      SYNC_CONFIG_DATABASE: false
      SYNC_CONFIG_MISC: false
      SYNC_CONFIG_DEBUG: false
      SYNC_GRAVITY_DHCP_LEASES: false
    networks:
      - pihole_pihole
networks:
  pihole_pihole:
    external: true
x-dockge:
  urls:
    - https://github.com/lovelaze/nebula-sync
    - https://technotim.live/posts/pihole-sync-nebula/
